### ISSUE TITLE
Docs: Feedback for Get Started with Embedded Hazelcast on Kubernetes

### ISSUE THREAD

**Issue by B-apt** [hazelcast-guides/hazelcast-embedded-kubernetes#7]
Hi, I have some feedback about [this page](https://github.com/hazelcast-guides/kubernetes-embedded/edit/master/docs/modules/ROOT/pages/kubernetes-embedded.adoc)

It's missing crucial part about Hazelcast configuration to get it working in Kubernetes. I add to explore the documentation of the now-deprecated Hazelcast plugin, in an older tag ([here](https://github.com/hazelcast/hazelcast-kubernetes/blob/1.5.x/README.md)) to find my informations.

In the current documentation, we can see the content of hazelcast.yaml

```yaml
hazelcast:
  network:
    join:
      multicast:
        enabled: false
      kubernetes:
        enabled: true
```

but it's not sufficient. You have to add some options to the kubernetes plugins, for exemple, in Kubernetes API mode:

```yaml
hazelcast:
  network:
    join:
      tcp-ip:
        enabled: false
      multicast:
        enabled: false
      kubernetes:
        enabled: true
        namespace: k8s-project-namespace
        service-name: my-svc-name
```

More infos are available in the documentation of the old plugin.
